version: '2'

services:
  kirin_config:
    image: {{env.docker_image_kirin_conf}}:{{env.current_docker_tag}}
    stdin_open: true
    restart: on-failure

  kirin:
    ports:
     - "{{env.kirin_port}}:{{env.kirin_port}}"
    image: {{env.docker_image_kirin}}:{{env.current_docker_tag}}
    restart: always
    volumes_from:
     - kirin_config
    logging:
      driver: "syslog"
      options:
        syslog-address: "{{env.protocole_syslog}}://{{env.host_syslog}}:{{env.port_syslog}}"
        syslog-facility: "local7"
        tag: "kirin"

    environment:
      VIRTUAL_HOST: {{env.kirin_host}}

  kirin_background:
    image: {{env.docker_image_kirin}}:{{env.current_docker_tag}}
    restart: always
    volumes_from:
     - kirin_config
    command: python ./manage.py load_realtime
    logging:
      driver: "syslog"
      options:
        syslog-address: "{{env.protocole_syslog}}://{{env.host_syslog}}:{{env.port_syslog}}"
        syslog-facility: "local7"
        tag: "kirin-background"

networks:
  default:
    external:
      name: canaltp
