version: "2"

services:

    kirin_db:
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_USER: "kirin"
            POSTGRES_PASSWORD: "kirin"
            POSTGRES_DB: "kirin"

    kirin_redis:
        image: redis:5-alpine
        restart: always

    kirin_rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always

networks:
  default:
    external:
      name: kirin_network
